### ISSUE TITLE
'WinElement' object has no attribute 'acc_role'

### ISSUE THREAD

**Issue by gooops** [F1ashhimself/UISoup#19]
File "D:\ProgramData\Anaconda3\lib\site-packages\uisoup\interfaces\i_element.py", line 300, in __str__
    self.acc_role,
AttributeError: 'WinElement' object has no attribute 'acc_role'

**Comment by F1ashhimself** [comment]
Hi there. Thanks for your report.

You can use version 2.5.5 now https://pypi.python.org/pypi/UISoup/2.5.5
